#YAML for construction
UDERON_CONSTANTS:
    FILES_TO_BUILD:
        html:
            - error.php
            - index.php
            - list.php
            - login.html
            - slist.php
    TEMPLATE_PARAMS:
        css_version: 1.41
    BUILD_DIR: uderon.com
