#YAML for construction
UDERON_CONSTANTS:
    - FILES_TO_BUILD:
        - html:
            - error:
                - error.php: index.php
            - index.php
            - list.php
            - login.php
            - slist.php
        - php:
            - pidcheck:
                - admin.php
                - found.php
                - notfound.php
    - TEMPLATE_PARAMS:
        - css_version: 1.41
    - BUILD_DIR: uderon.com
